### ISSUE TITLE
Bug: S3 Marketplace photo upload ignores EXIF rotation

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#95] opened 2017-01-06 18:03 UTC
Confirmed on live site.

Browsers: Firefox, Chrome (these are the only ones I tried)

If a user uploads a photo with EXIF rotation tags to their marketplace profile, they will be surprised to see the image rotated in an unexpected way. Here's an example of my profile: 

![profile-rotated-photo](https://cloud.githubusercontent.com/assets/6644016/21727604/f18a9770-d3f6-11e6-94e1-9182f40d9412.jpg)

Here's the original photo for testing purposes: 
[img_20170106_095314](https://cloud.githubusercontent.com/assets/6644016/21727625/13abd8dc-d3f7-11e6-9486-c9bb19973653.jpg)

Depending on the camera and the orientation of the photo, some photos contain rotation data so they can be rendered in a particular orientation. (See [this for more info on the state of EXIF rotation](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/) on the web (as of 2012)).

Some solution(s):

- we tell users to manually strip EXIF info with their own tools (bad solution, but a workaround)
- when we process the upload, we rotate the image to match the EXIF tag and strip the EXIF rotation tag so the image is rendered consistently across browsers
- allow the user to rotate the image on the front end so it matches their expectation

**Comment by IagoSRL** [comment] 2017-01-20 17:15
Hi @situatedbit,

Thanks to remember this and the resource (good link, I didn't know about the *mirror* orientations values :-S).
We discovered this some time ago (see 997), and added a workaround at the *aboutMe* activity (for the profile picture), only when uploading the picture, that is a button to rotate the picture (your point 3 ;-).

The ideal is to enable this at the *work photos* section quickly; we can let the button to allow rotation not only when uploading a new one but for edit a previous one too. The mirroring problem, I suppose is not so usual so we can forget for now?

**Comment by situatedbit** [comment] 2017-01-20 17:46
I didn't realize that there was a rotate option for the bio profile. I agree. Let's add the same behavior to the work photos.

**Comment by IagoSRL** [comment] 2017-02-06 17:25
Just enabled at *dev* rotation of previously saved picture-profile, next step is replicate all the feature at work photos

**Comment by IagoSRL** [comment] 2017-02-09 00:02
Implemented this completely. As unexpected work, I had to reimplement C# code to rotate a photo (previous worked only well on square images, anything else was a disaster), and touch other details at upload photo code, resize and filename editing utils.

**It's at dev, for testing**

Changes:
- Account / profile picture can be edited to be rotated (previously, could only be rotated just when a photo is chosen and at preview, before is actually uploaded).
- Work photos: new button on each photo (on hover / tap the photo) to rotate. Can be done before upload or at a photo previously uploaded.
- When a work photo is edited (rotated previously uploaded photo), a version number is attached to the URL, based on date-time (using cache busting), preventing displaying the old image because of browser cache.
- Fixed some strange details when resizing some photos (mostly changing the InterpolationMode).
- Like before, all work photos are landscape with fixed sizes, but a uploaded photo that is (originally or after apply rotation) portrait is saved as 'editable' photo in portrait (before was forced to landscape, reducing it's size); that allow to be rotated after uploaded while keeping original size (don't getting downsized on every rotation with white space around); optimized files based on that are still landscape (the ones actually displayed to end user).
- Every photo rotated is previewed, and with a simple animation (easy css transition :-)

**Comment by IagoSRL** [comment] 2017-02-09 00:04
Latest minor change: at profile picture, when a new photo is picked, the preview rotation value is reset

**Comment by joshdanielson** [comment] 2017-02-09 01:15
@IagoSRL tested and working! I uploaded a photo that was originally landscape that I changed to portrait in apple's photo program and it was uploaded correctly as portrait. 

@situatedbit you should probably test, too.

**Comment by situatedbit** [comment] 2017-02-09 17:30
I've tested work images and profile images. Looks good on dev.

My only challenge is that I'm unable to rotate work images on my phone
browser (or in the app). There's a button for rotating under the profile
image, but I have to hover with a pointer over the work photos.
Unfortunately, photos taken with phones often include EXIF rotation data.

**Comment by IagoSRL** [comment] 2017-02-09 18:20
Thanks for the feedback.

I tested on Chrome (latest) at Android (7.1.1) and it worked fine. Tap on photo works. But I understand both points @situatedbit comments:
- Maybe tap on photo is not obvious in mobile to discover the edition tools (rotate, move, delete).
  - At other apps is usual to swipe over an item for extra options (for example at emails), but maybe that is not expected on a item with the appearance of a photo?
  - We can move buttons to below as a toolbar on each photo (only on mobile or the feature feels intuitive at desktop too?). Some user testing on this or not?
- About mobile EXIF:
  - I had no problems but I can understand that a problem may arise if the browser/engine detects EXIF: the preview will be correct because has EXIF rotation and browser understand that, but server not, so will 'see' it with a different orientation and what initially appeared fine on preview, later appears rotated; and because after save the photos, the app moves from the activity to back, user cannot see how photo was procesed by server. @situatedbit If I understand it this what happened to you, right? What device and browser?
  - then: our rotate feature works as a fix for the EXIF problem just when the mobile camera sets a EXIF rotation but the web engine/browser does Not understand it (same as our server), so preview appears incorrectly rotated and user can click to rotate to fix it. Server will do the same and everything OK.
  - we need EXIF detection on server (I will research this)
  - or to strip EXIF info on the preview

**Comment by situatedbit** [comment] 2017-02-09 19:29
I think we should move forward with it. I'll be sure to keep my eye on it during user testing. Though, generally we should avoid hiding something like this behind a swipe or a tap if it's related to the primary task on a screen/page.

Re: differences on browser + server. I didn't actually see this, though I suppose it could happen. Have you seen it happen?

Otherwise, looks good.

**Comment by IagoSRL** [comment] 2017-02-10 10:47
I didn't see the commented EXIF problem, just guessing may be an edge case (based in part of comments at [the referenced link](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/)). I need to force a test to verify; there is a chance that does not happens as I commented because the preview at browser is done with a library that prints the image in a canvas, and *maybe* that kind of processing ignores EXIF too (?). Proofs needed.

@situatedbit I was thinking this was the problem you commented (I understood bad).

If no problems found on testing (I suppose you tried the same situation that created a problem originally and now seems fixed), yes I agree with push forward.
Will try the EXIF trick and comment.

Created #241 to research the commented usability of edition toolbar.

**Comment by IagoSRL** [comment] 2017-02-10 19:53
(sorry the loooong post)

## Possible bug: EXIF orientation respected at preview but not at server
This is the summary of the *maybe* bug I commented yesterday. And my research today.

I tested with an image where I set the EXIF orientation property value manually ([using](http://leancrew.com/all-this/2009/04/derotating-jpegs-with-exiftool/) [exiftool](http://www.sno.phy.queensu.ca/~phil/exiftool/), and verifying the result with other programs, like [Gimp](https://www.gimp.org/) and [PhotoMe](http://www.photome.de/) that detect that orientation. I tried too with Windows 7 Image Preview, that fails detecting orientation value (as commented as several blogs), and I tested opening with latest Firefox and Chrome, both detects orientation and show the photo correctly rotated based on EXIF value.

### Webapp
Then, I tried to choose that image at our Work Photos form: the preview does **not** respect the EXIF orientation value, so is not orientated properly. Both Firefox and Chrome at desktop and Android. Even looking as a problem, is not because it previews the same our server "sees", then the result after the image is processed and saved at the server (and with user rotation if any) will be the expected from preview.
Minor usability problem: after user chooses a photo with EXIF orientation, the preview display is not orientated as expected; but he can click to rotate, save, and everything fine.

*Curious note:* When attaching the orientated photo using Inbox by Gmail, is previewed without respect EXIF orientation, while at Gmail is respected, same browser.

**Preview EXIF support:** The [uploader](https://blueimp.github.io/jQuery-File-Upload/) library we use has a module to detect EXIF orientation (that we have downloaded at /vendor folder but not loaded in the app); but if we use it, we need to add support at server too to prevent different processing, and then the problem I commented yesterday would happen.

### Native app
The way we preview photos at App is different: the Phonegap plugin give us a URL to a local resource where the image lives (both: selected from our gallery, or the temporary photo we just took), and we use that at a normal *img* tag, no special processing of the photo is needed for preview (as happens in webapp).
Then, there is a chance where EXIF orientation is respected at preview, there creating the commented bug. And that depends on the underlaying webview and version, not a library where we have disabled/enabled EXIF rotation.

**Android:** I tried latest release app at latest Android 7.1.1, with webview updated (it supports EXIF orientation), and the preview does NOT respects orientation, so everything is fine :-)

**iPhone:** I tried latest release app at latest iOS 10.2.1, (app is using WKWebView rather than UIWebView; it supports EXIF orientation); and the preview DOES respects orientation, so a **problem may arise**. I uploaded the image there as is (no rotated at the app), and everything went fine (the processed result image appears rotated as EXIF says). *I do not understand what happens, maybe EXIF metadata gets removed by iOS for the upload?*

### Conclusion
There is the minor usability (fixable with the new *rotate* tool), the strange case at iOS and fear that at the native app, at any moment this may change (because of a change on system webview behavior) and become a problem.

### Notes (maybe just for me)
Found ways [to read EXIF orientation from C#](https://stackoverflow.com/questions/226973/how-to-edit-exif-data-in-net). With that (knowing the orientation code and parsing values) we must be able to rotate and flip at server depending on EXIF in order to get a manipulated image without the orientation property but oriented as expected.

**Comment by IagoSRL** [comment] 2017-02-13 17:51
As conclusion of my previous long post:
- I think this is complete, worked fine on any test I did, just waiting if you have a comment or more testing wanted.
- Still some *doubts* exists, something to keep an eye on it; it seems the bug can arise at some edge case on native apps, but unable to reproduce now; if it happens will require us to finally implement server detection of EXIF rotation, and as collateral change forcing to enable EXIF rotation at webapp preview. Can create a low priority issue for this one.

**Comment by situatedbit** [comment] 2017-02-13 18:02
I do not feel this needs more testing at the moment.

**Comment by IagoSRL** [comment] 2017-02-13 20:43
Opened #246 for the commented *edge case* details, low priority. Closing and merging this.

**Closed by IagoSRL** 2017-02-13 20:43 UTC
Labels: Bug: S3, F: Listings, T4: Ready for Testing
