### ISSUE TITLE
Partner Gig Posting

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#820] opened 2018-02-21 15:55 UTC
## Epic Story
As a   small business partner or internal department of the CCC, I want post gigs available to students and have the ability for them to express interest so that we can set up a consultation to see if they're a good fit for the work.

**Comment by joshdanielson** [comment] 2018-06-08 03:19
@IagoSRL can you review these copy changes, especially the email template ones? I used @(info.serviceProfessional.firstName) and not sure if that's a valid variable.

I am back in the office tomorrow so let's please wrap anything remaining and shoot for a release ASAP.

**Comment by IagoSRL** [comment] 2018-06-08 13:15
Will do, merge and push changes and chat after some testing.

**Comment by IagoSRL** [comment] 2018-06-11 16:03
@joshdanielson Your copy changes are OK. The `@(info.serviceProfessional.firstName)` is valid, while previous `@(info.serviceProfessional.publicName)` uses the business name if available, fallback to firstName + lastName.

I pushed to the branch and *dev* latest changes, so test sign-up at ccc-partners landing, checking and not-checking the checkbox, try onboarding (additional step for checkbox/organization), and posting.
Should be complete, If I recall all the details.

**Comment by joshdanielson** [comment] 2018-06-11 16:24
@IagoSRL got an error in the sign-up on the landing page (I checked the box):
![screen shot 2018-06-11 at 9 22 18 am](https://user-images.githubusercontent.com/1202838/41244207-350fd79c-6d59-11e8-8148-9a28684ffb68.png)

**Comment by joshdanielson** [comment] 2018-06-11 16:28
@IagoSRL can we move that checkbox to the first step of the onboarding with the contact info (not sure what the extra step looks like) and they get the extra step if they check it then? It seems out of place where it is.

Couple other minor things on the landing page:
- [ ] can we change "Sign up for free" to "Get started for free"? It can be in all signups and the "Sign up with email" sounds fine still so no need to change those. 
- [ ] can you remove the "Get started" buttons? It doesn't make sense for them since the sign up form is there already.

**Comment by IagoSRL** [comment] 2018-06-11 17:13
- 'get started' Buttons removed at ccc-partners landing
- 'get started for free' used for all client sign-ups (for professionals still says 'Your first listing is free')

**Comment by IagoSRL** [comment] 2018-06-11 17:15
Doing the checkbox change, it requires to add REST API stuff to profile (the flag was set at signup). Need to check if onboarding step appears when checking in a step or do other changes.

**Comment by joshdanielson** [comment] 2018-06-11 17:24
@IagoSRL not seeing it yet:
![screen shot 2018-06-11 at 10 23 24 am](https://user-images.githubusercontent.com/1202838/41247023-9897c920-6d61-11e8-8d3c-ff6ecebef658.png)

**Comment by IagoSRL** [comment] 2018-06-11 17:31
The new entry is only if your user has already the isOrganization flag check as true (from the sign-up).

Now, in my branch I have the change to be able to change that flag from contact-information but the problem is that if the user at ccc-partners doesn't set the flag then the onboarding enters in the default welcome (because I was checking the flag in order to skip that step).

**Comment by joshdanielson** [comment] 2018-06-11 17:37
@IagoSRL okay, kinda confused but also know it's confusing. What about putting the organization-info module in public-contact-info and it appears if the user checks the box "I"m hiring on behalf of my organization"? Just brainstorming here.

**Comment by IagoSRL** [comment] 2018-06-11 17:42
Yeah, I though on that, since the user may expect to have the possibility to input some organization info after check that and not in another place. It's not so bad, since after editing the contact info it goes to the userProfile where appears the new entry, or next step at onboarding.

Anyway, that doesn't fix the problem with sign-up going to 'welcome' step.

**Comment by joshdanielson** [comment] 2018-06-11 17:43
@IagoSRL ahh...missed the real problem, sorry.

**Comment by IagoSRL** [comment] 2018-06-11 18:11
Did a change at server for that (*dev*), other changes on front-end just in the branch.

**Comment by joshdanielson** [comment] 2018-06-11 19:33
@IagoSRL I don't think the last commit went to the server (not working on the branch...still goes to welcome). I did get to the public-contact-info and check the hire on behalf of organizations but then it went to the home page with the pop-up "Search and book local services". I'm assuming it's supposed to go to the organization-info. Then it should to go post a project (directly to the first question.

**Comment by joshdanielson** [comment] 2018-06-11 19:36
@IagoSRL wait...didn't build the app just the landing pages so probably why. Hard to test both, right?

**Comment by joshdanielson** [comment] 2018-06-11 19:36
Thinking it has to be on dev for me to test properly

**Comment by joshdanielson** [comment] 2018-06-11 20:59
@IagoSRL did some more testing on the posting/application and found a minor thing. Can you add organization info to the posting (if there is some)? Thinking the main heading being Organization Info and then bold headings for Organization's name, website, and Description of organization.
![screen shot 2018-06-11 at 1 56 29 pm](https://user-images.githubusercontent.com/1202838/41256818-9f2d2fdc-6d7f-11e8-86bb-6f56e210dbfc.png)

**Comment by joshdanielson** [comment] 2018-06-12 19:58
@IagoSRL just tested on dev...onboarding went well from the landing page. However, got a couple errors when submitting the posting:
![screen shot 2018-06-12 at 12 53 39 pm](https://user-images.githubusercontent.com/1202838/41313964-2de71ff6-6e40-11e8-9204-7cc325195cfd.png)
Even with the error, it still somehow submitted so that I got this email:
![screen shot 2018-06-12 at 12 55 33 pm](https://user-images.githubusercontent.com/1202838/41313987-3d51fb46-6e40-11e8-9b78-fc59a97ddf59.png)
Then I got another error clicking on "View Posting" (I was logged in as the user who got the email on a different browser so not that):
![screen shot 2018-06-12 at 12 55 50 pm](https://user-images.githubusercontent.com/1202838/41314010-51f63fb2-6e40-11e8-86b8-e19704589805.png)

**Comment by IagoSRL** [comment] 2018-06-13 09:46
Oh, silly. I had a mistake in the SQL saving the responses after adding the 'label' column and some data was placed at wrong column. I fixed it in the code and removed your latest user posting that had that wrong data, new ones should go fine

**Comment by IagoSRL** [comment] 2018-06-13 09:47
PS: was the same error for save and load actions.

**Comment by IagoSRL** [comment] 2018-06-13 10:28
Pushed the changes that includes the organization information (if any) at the posting viewer.

**Comment by IagoSRL** [comment] 2018-06-14 10:58
@joshdanielson I reviewed your touch ups and fixed the usage of `createSubsectionNavBar` at activities, including the special case for `suggested-postings` (that behaves first as 'section' and as 'subsection' when selecting an item).
Opened too an issue for the organization's logo.
Closing, merging into master and releasing.

**Closed by IagoSRL** 2018-06-14 10:58 UTC
Labels: C: New Feature, Epic, F: Postings
