### ISSUE TITLE
Bug S2: Profile link appears in mobile menu when not logged in

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#370] opened 2017-04-27 17:41 UTC
Currently on dev but _not_ live.

On the narrow layout, when I'm not logged in there is a link to my profile. It shouldn't be there unless I'm logged in:

![profile-link](https://cloud.githubusercontent.com/assets/6644016/25496485/06354c2e-2b36-11e7-8edf-568575c8b93f.jpg)

**Comment by ardanak** [comment] 2017-07-07 19:20
@situatedbit I wasn't able to reproduce the error in chrome dev tools with the mobile device setting. Am I missing something?

**Comment by joshdanielson** [comment] 2017-07-10 21:02
@ardanak and I couldn't reproduce so closing.

**Closed by joshdanielson** 2017-07-10 21:02 UTC
Labels: Bug: S2, D: Unable to Reproduce, F: General Site, Good first issue
